Repository Axel-Pion-MDS/M1_Project_Timer_Back, pull requests merged in 2022-12, with the labels that each got.

#5 Feature user organization
  app/settings.py
  app/urls.py
  organization/admin.py
  organization/normalizers.py
  organization/views.py
  requirements.txt
  service/tokenDecode.py
  user_organization/__init__.py
  user_organization/admin.py
  user_organization/apps.py
  user_organization/forms.py
  user_organization/migrations/__init__.py
  user_organization/models.py
  user_organization/normalizers.py
  user_organization/tests.py
  user_organization/urls.py
  user_organization/views.py
Labels: enhancement

#6 Feature organization
  app/settings.py
  app/urls.py
  organization/__init__.py
  organization/admin.py
  organization/apps.py
  organization/forms.py
  organization/migrations/__init__.py
  organization/models.py
  organization/normalizers.py
  organization/tests.py
  organization/urls.py
  organization/views.py
  requirements.txt
  service/tokenDecode.py
  user/admin.py
  user/forms.py
  user/models.py
  user/views.py
  user_organization/__init__.py
  user_organization/admin.py
  user_organization/apps.py
  user_organization/forms.py
  user_organization/migrations/__init__.py
  user_organization/models.py
  user_organization/normalizers.py
  user_organization/tests.py
  user_organization/urls.py
  user_organization/views.py
Labels: enhancement

#7 Feature team
  .gitignore
  app/settings.py
  app/urls.py
  app/views.py
  role/views.py
  service/errors.py
  service/send_response.py
  service/verify_method.py
  team/__init__.py
  team/admin.py
  team/apps.py
  team/forms.py
  team/migrations/__init__.py
  team/models.py
  team/normalizers.py
  team/tests.py
  team/urls.py
  team/views.py
Labels: enhancement

#9 docs: add MIT licence to the project
  LICENCE.md
Labels: documentation

#8 Feat jwt token
  .env.sample
  requirements.txt
  user/urls.py
  user/views.py
Labels: feature :zap:, to review :rotating_light:

#10 [URGENT] Fix user
  user/views.py
Labels: fix :ambulance:, refacto :art:

#11 fix: check jwt token and add role in token
  service/tokenDecode.py
  user/views.py
Labels: to review :rotating_light:, refacto :art:

#12 Feature/project
  app/settings.py
  app/urls.py
  project/__init__.py
  project/admin.py
  project/apps.py
  project/forms.py
  project/migrations/__init__.py
  project/models.py
  project/normalizers.py
  project/tests.py
  project/urls.py
  project/views.py
  service/verify_user_in_model.py
  user/views.py
Labels: feature :zap:, to review :rotating_light:

#15 feat: accept localhost cors allowed
  app/settings.py
Labels: feature :zap:, to review :rotating_light:

#17 Docs swagger
  app/settings.py
  app/urls.py
  app/views.py
  documentation/swagger_documentation.yaml
  organization/views.py
  project/views.py
  requirements.txt
  role/views.py
  service/tokenDecode.py
  task/views.py
  team/views.py
  user/urls.py
  user/views.py
  user_organization/views.py
  user_task/views.py
Labels: documentation :memo:, to review :rotating_light:
